# Numpy

In [1]:
import numpy as np

### Creating Arrays

In [6]:
myList = [1, 2, 3]
x = np.array(myList)
x

array([1, 2, 3])

In [67]:
y = np.array([7,8,9])
y

array([7, 8, 9])



Multidimensional arrays:

In [68]:
m = np.array([[1, 2, 3], [4, 5, 6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
m.shape

(2, 3)

In [70]:
l = np.arange(0, 30, 3)
l

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [71]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [72]:
#n = n.reshape(1, 15)
#n

In [73]:
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [74]:
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [75]:
o.resize #resize changes the array in place, different from reshape
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [76]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [77]:
np.ones((2, 3, 4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [48]:
np.ones((2, 3, 4, 5))

array([[[[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]]],


       [[[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]]]])

In [78]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [79]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [80]:
y

array([7, 8, 9])

In [81]:
np.diag(y)

array([[7, 0, 0],
       [0, 8, 0],
       [0, 0, 9]])

In [82]:
np.array([1, 2, 3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [83]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [84]:
p = np.ones((2, 3), int) #passing int converts the datatype to int from float
p

array([[1, 1, 1],
       [1, 1, 1]])

In [85]:
np.vstack((p, p*2)) #Stack vertically

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [86]:
np.hstack((p, p*2))  #stack horizontally

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [89]:
print(x, y)

[1 2 3] [7 8 9]


### Operations

In [91]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 8 10 12]
[-6 -6 -6]
[ 7 16 27]
[ 0.14285714  0.25        0.33333333]


In [92]:
print(x**2)

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [94]:
x.dot(y)

50

In [103]:
z = np.array([y, y**2])
print(z)
print(len(z)) #length of rows of the array

[[ 7  8  9]
 [49 64 81]]
2


In [104]:
z.shape

(2, 3)

In [108]:
z.T     #Transpoing the array

array([[ 7, 49],
       [ 8, 64],
       [ 9, 81]])

In [109]:
z.T.shape

(3, 2)

In [125]:
z.dtype     #datatype of the elements in the array

dtype('int32')

In [126]:
z.astype('f')

array([[  7.,   8.,   9.],
       [ 49.,  64.,  81.]], dtype=float32)

In [127]:
z.dtype

dtype('int32')

### Math Functions 

In [128]:
a = np.array([-4, -2, -1, 0, 1, 4, 5, 6])

In [129]:
a.sum()

9

In [131]:
a.max()

6

In [132]:
a.min()

-4

In [133]:
a.mean()

1.125

In [134]:
a.std()

3.3330729064933458

argmax and argmin return the index of the maximum and minimum values in the array.

In [137]:
a.argmax()

7

In [138]:
a.argmin()

0

### Indexing and Slicing

In [142]:
s = np.arange(19)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324])

In [144]:
s[0], s[7], s[-1]

(0, 49, 324)

In [145]:
s[1:9]

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [146]:
s[:5]

array([ 0,  1,  4,  9, 16])

In [147]:
s[:-5]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169])

In [148]:
s[-5]

196

In [149]:
s[-5::2]

array([196, 256, 324])

In [152]:
s[0::5]

array([  0,  25, 100, 225])

In [158]:
r = np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [168]:
r = r.reshape((6, 6))

In [169]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [170]:
r[2, 2]

14

In [173]:
r[3, 3:6]

array([21, 22, 23])

In [175]:
r[-2, :-1]

array([24, 25, 26, 27, 28])

In [177]:
r[-1, ::2]

array([30, 32, 34])

In [178]:
r[r>30]

array([31, 32, 33, 34, 35])

In [181]:
r[r>30] = 30  #Modify the values to 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Copying and Modifying

In [184]:
r2 = r[:3, :3] #Slice of r
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [186]:
r2[:] = 0 #change the all values in r2 to 0 
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [187]:
#But it changes the values for "r" as well
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [188]:
#assign the value to a copy variable to avoid this overwrite 
rCopy = r.copy()
rCopy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [194]:
rCopy[:] = 10
print(r, '\n')
print(rCopy)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]] 

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


### Iterating over Numpy Arrays

In [199]:
test = np.random.randint(0, 10, (4, 3))
test

array([[1, 6, 7],
       [1, 8, 9],
       [7, 1, 5],
       [9, 2, 7]])

In [200]:
#iterate through the rows
for i in test:
    print(i)

[1 6 7]
[1 8 9]
[7 1 5]
[9 2 7]


In [204]:
print(len(test),"\n")
#iterate through index of the rows
for i in range(len(test)):
    print(test[i])

4 

[1 6 7]
[1 8 9]
[7 1 5]
[9 2 7]


In [211]:
#use enumerate to Iterate by row and index:
for i,j in enumerate(test):
    print("row",i, "is: ", j)

row 0 is:  [1 6 7]
row 1 is:  [1 8 9]
row 2 is:  [7 1 5]
row 3 is:  [9 2 7]


In [212]:
test2 = test**2
test2

array([[ 1, 36, 49],
       [ 1, 64, 81],
       [49,  1, 25],
       [81,  4, 49]])

In [213]:
#use zip to iterate over multiple iterables
for i, j in zip(test, test2):
    print(i, " + ", j, " = ", i+j )

[1 6 7]  +  [ 1 36 49]  =  [ 2 42 56]
[1 8 9]  +  [ 1 64 81]  =  [ 2 72 90]
[7 1 5]  +  [49  1 25]  =  [56  2 30]
[9 2 7]  +  [81  4 49]  =  [90  6 56]


In [214]:
type(lambda x: x+1) 

function